dependencies:
  - python==3.8.10
  - pip
  - pip: 
    - spacy==2.2.4
    - viola==0.3.8
    - language-tool-python==2.6.1
    - fastai==2.5.2 #==2.2.7
    - fastbook==0.0.18 #==0.0.16
    - ipywidgets==7.6.3 #==7.5.0
    - pydicom==2.2.2 #==2.1.2
    - kornia==0.5.11 #==0.4.1
    - scikit-image==0.18.3 #==0.16.2 