#versions: myenv, binderenv, myenvextras
dependencies:
  - python==3.8.10 #
  - pip==21.0 #
  - pip: 
    - spacy==2.3.5 #==2.2.4
    - viola==0.3.8 #, ==0.2.16
    - fastai==2.2.7 #==2.5.2
    - Pillow==7.0.0 #